apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: grafana
name: grafana
namespace: grafana
version: 6.26.1
repo: https://grafana.github.io/helm-charts
releaseName: demo
valuesInline:
  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 3000
      # targetPort: 4181 To be used with a proxy extraContainer
    annotations: {}
    labels: {}
    portName: service
  rbac:
    create: true
    namespaced: true
    pspEnabled: false
  serviceMonitor:
    enabled: false
    labels: {}
    interval: 1m
    scheme: http
    tlsConfig: {}
    scrapeTimeout: 30s
    relabelings: []
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
    - grafana-test.demo.akuity.io
  resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi