apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: grafana
  releaseName: test
  version: 6.26.1
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  namespace: grafana

patches:
- target:
    kind: Deployment
    version: v1
    group: apps
  path: patch-deployment-rollout.yaml