apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig/rollout-transform.yaml

openapi:
  path: kustomizeconfig/rollout_cr_schema.json

resources:
- all.yaml

