apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - config/rollout-transform.yaml

helmCharts:
- name: grafana
  releaseName: demo
  version: 6.26.1
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  namespace: grafana

resources:
- services.yaml

patches:
- target:
    kind: Deployment
    version: v1
    group: apps
  path: patch-deployment-rollout.yaml

openapi:
  path: config/rollout_cr_schema.json