- op: replace
  path: /kind
  value: Rollout
- op: replace
  path: /apiVersion
  value: argoproj.io/v1alpha1
- op: replace
  path: /spec/replicas
  value: 3
- op: add
  path: /spec/strategy
  value:
    canary:
      canaryService: grafana-desired
      stableService: grafana-stable
      steps:
        - setWeight: 30
        - pause: {}
        - setWeight: 60
        - pause:
            duration: 10
