apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: grafana-rollout
spec:
  replicas: 2
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: demo-grafana
  strategy:
    blueGreen:
      activeService: demo-grafana
      previewService: demo-grafana-preview
      autoPromotionEnabled: false