service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000
    # targetPort: 4181 To be used with a proxy extraContainer
  annotations: {}
  labels: {}
  portName: service

rbac:
  create: true
  namespaced: true
  pspEnabled: false

serviceMonitor:
  enabled: false
  labels: {}
  interval: 1m
  scheme: http
  tlsConfig: {}
  scrapeTimeout: 30s
  relabelings: []

ingress:
  enabled: true
  hosts:
  - grafana-test.demo.akuity.io
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
  tls:
  - hosts:
    - grafana-test.demo.akuity.io


resources:
 limits:
   cpu: 300m
   memory: 512Mi
 requests:
   cpu: 100m
   memory: 128Mi